# Site Settings
name: STUDITEMPS Code Guide
description: Richtlinien zur Entwicklung von flexiblem, wartbarem und best&auml;ndigem HTML und CSS.
url: http://BackendButters.github.io/code-guide/

# Build Settings
markdown: kramdown # rdiscount
permalink: pretty
highlighter: rouge
