# Site Settings
title: STUDITEMPS.TECH Front End Code Guide
description: Unsere STUDITEMPS.TECH Richtlinien für die Entwicklung von flexiblem, wartbarem und beständigem HTML und CSS.
baseurl: "" # "/frontend-code-guide" for production

# Build Settings
markdown: redcarpet
permalink: pretty
highlighter: pygments
exclude: ['README.md', 'LICENSE.md', 'package.json', 'gulpfile.js', 'node_modules']
